name: Plugin Bug or Incompatibility with another Plugin
description: Report issues with plugin incompatbility or other behavior related issues. Not for config help or any errors, contact us on Discord for the former, and use the right issue template for the latter.
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a bug here, please make sure you are on the latest version of TradeShop or another supported version.
        Forks of TradeShop receive no support here. If you are using a fork, please make sure that this issue also happens when using TradeShop.

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)
      description: |
        Run `/version` and `/ts help` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the actual output outputs so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        Lastly, if you use a pre-release (DEV build), add the date and time of the release as well, as often many pre-releases share the same version tag.
        <details>
        <summary>Example</summary>

        ```
        > version
        [20:34:42 INFO]: This server is running Paper version git-Paper-540 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
        [20:34:42 INFO]: Checking version, please wait...
        [20:34:42 INFO]: Previous version: git-Paper-538 (MC: 1.16.5)
        [20:34:42 INFO]: You are running the latest version
        > ts help
        [00:13:35] [Server thread/INFO]:
        [00:13:35] [Server thread/INFO]: TradeShop 2.3.0-DEV by Lori00 & KillerOfPie
        [00:13:35] [Server thread/INFO]:
        [00:13:35] [Server thread/INFO]: /tradeshop   Display help message
        [00:13:35] [Server thread/INFO]: /ts help   Display help message
        [00:13:35] [Server thread/INFO]: /ts setup   Display shop setup tutorial
        [00:13:35] [Server thread/INFO]: /ts bugs   Report bugs to the developers
        [00:13:35] [Server thread/INFO]: /ts playerlevel If Internal Permissions is enable this allows the getting and setting of player permission levels.
        [00:13:35] [Server thread/INFO]: /ts reload   Reload configuration files
        [00:13:35] [Server thread/INFO]:                                                    
        ```

        </details>
    validations:
      required: true
      
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).
          required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        If you have filled in all the required information, submit the issue. We will reply as soon as possible so please check back frequently.
        **Disclaimer:** Several parts of this document were taken from the [PaperMC](https://github.com/PaperMC/Paper) project, which holds the credit.
